CALL conv(inp, convLayers(1)%weights, convLayers(1)%biases)
CALL max_pool(inp,maxpoolLayers(1))
CALL conv(inp, convLayers(2)%weights, convLayers(2)%biases)
CALL max_pool(inp,maxpoolLayers(2))
CALL linear_layer(inp, linLayers(1))
CALL linear_layer(inp, linLayers(2))
CALL linear_layer(inp, linLayers(3))
CALL linear_layer(inp, linLayers(4))
CALL lstm(inp, hid1, cell1, lstmLayers(1)%whh, lstmLayers(1)%wih, lstmLayers(1)%bih, lstmLayers(1)%bhh)

