"""Render a plan as a self-contained C source/header pair."""
from .plan import Plan

_CTYPE = {"f32": "float", "f64": "double"}
_ACT_C = {"relu": "{v} > 0.0 ? {v} : 0.0", "tanh": "tanh({v})",
          "sigmoid": "1.0 / (1.0 + exp(-({v})))"}
_DTYPE_CODE = {"f32": 0, "f64": 1}


def _c_string(s: str) -> str:
    """Escape a plan-supplied (ASCII) name as a C string literal body."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _weight_size(shape) -> int:
    size = 1
    for d in shape:
        size *= d
    return size


def _weight_index_c(weight_by_symbol: dict, symbol: str, n_in: int, n_out: int) -> str:
    """Decide the accumulation index order from the layout rule.

    A transB=1 Gemm weight has ONNX shape (n_out, n_in), stored row-major and
    indexed w[i * n_in + j] directly. A transB=0 weight, or any MatMul
    weight, has ONNX shape (n_in, n_out), indexed w[j * n_out + i]. Unlike
    the Fortran side, C never reverses the dimensions, so no transposition
    happens anywhere.
    """
    spec = weight_by_symbol[symbol]
    if spec.shape[0] == n_out:
        return f"i * {n_in} + j"
    if spec.shape[0] == n_in:
        return f"j * {n_out} + i"
    raise AssertionError(
        f"weight {symbol}: shape {spec.shape} matches neither n_in={n_in} nor n_out={n_out}")


def _fuse(ops):
    """Fuse each gemm with an immediately-following activation that consumes it.

    Producing a fused pair's intermediate (the gemm's own raw output) as a
    separate buffer would be legal but wasteful: nothing else ever reads it.
    Folding the activation into the same loop that computes the gemm's
    accumulator (as in the brief's gemm_small example) means the buffer
    assignment pass below never has to allocate storage for it at all.
    """
    steps, i, n = [], 0, len(ops)
    while i < n:
        op = ops[i]
        if op.kind == "gemm":
            nxt = ops[i + 1] if i + 1 < n else None
            if nxt is not None and nxt.kind in _ACT_C and nxt.inp == op.out:
                steps.append({"kind": "gemm", "out": nxt.out, "inp": op.inp, "length": op.n_out,
                              "weight": op.weight, "bias": op.bias, "n_in": op.n_in,
                              "n_out": op.n_out, "act": nxt.kind})
                i += 2
                continue
            steps.append({"kind": "gemm", "out": op.out, "inp": op.inp, "length": op.n_out,
                          "weight": op.weight, "bias": op.bias, "n_in": op.n_in,
                          "n_out": op.n_out, "act": None})
            i += 1
        else:
            prev_len = steps[-1]["length"] if steps else None
            steps.append({"kind": "act", "out": op.out, "inp": op.inp, "length": prev_len,
                          "act": op.kind})
            i += 1
    return steps


def _assign_buffers_c(plan: Plan, steps: list) -> tuple:
    """Same free-list scheme as plan._assign_buffers, run over the fused steps.

    Fusing folds each gemm+activation pair into a single step whose output
    name is the activation's, so a gemm's own raw output never gets a buffer
    of its own -- only the final name of each step does.
    """
    buffers = {"x": plan.input.shape[0], "y": plan.output.shape[0]}
    assignment = {plan.input.name: "x", plan.output.name: "y"}
    last_use = {}
    for i, s in enumerate(steps):
        last_use[s["inp"]] = i
    free, pool = [], 0
    for i, s in enumerate(steps):
        if s["out"] not in assignment:
            if free:
                sym = free.pop()
            else:
                sym = f"t{pool}"
                pool += 1
            assignment[s["out"]] = sym
            buffers[sym] = max(buffers.get(sym, 0), s["length"])
        if (s["inp"] in assignment and assignment[s["inp"]].startswith("t")
                and last_use.get(s["inp"]) == i):
            free.append(assignment[s["inp"]])
    return buffers, assignment


def emit_c(plan: Plan) -> tuple:
    ctype = _CTYPE[plan.dtype]
    header = _emit_header(plan, ctype)
    lines = []
    lines += _emit_source_head(plan, ctype)
    lines += _emit_load(plan)
    lines += _emit_init(plan)
    lines += _emit_infer(plan, ctype)
    source = "\n".join(lines) + "\n"
    return source, header


def _emit_header(plan: Plan, ctype: str) -> str:
    m = plan.model
    guard = f"ROSENNA_{m.upper()}_H"
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Generated by rosenna. Do not edit. */",
        "",
        f"int {m}_init(const char *path);",
        f"void {m}_infer(const {ctype} *restrict x, {ctype} *restrict y);",
        "",
        "#endif",
    ]
    return "\n".join(lines) + "\n"


def _emit_source_head(plan: Plan, ctype: str) -> list:
    m = plan.model
    hash_bytes = ", ".join(f"0x{b:02x}" for b in bytes.fromhex(plan.hash()))
    lines = [
        "/* Generated by rosenna. Do not edit. */",
        f'#include "{m}.h"',
        "",
        "#include <stdint.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        "#include <math.h>",
        "",
        f"static const unsigned char expected_hash[32] = {{ {hash_bytes} }};",
        "",
    ]
    for w in plan.weights:
        lines.append(f"static {ctype} {w.symbol}[{_weight_size(w.shape)}];")
    lines.append("")
    return lines


def _emit_load(plan: Plan) -> list:
    lines = [
        "static int load_tensor(FILE *f, const char *name, int namelen, long pos) {",
        "    fseek(f, pos, SEEK_SET);",
    ]
    for w in plan.weights:
        lines.append(
            f"    if (namelen == {len(w.name)} && memcmp(name, {_c_string(w.name)}, {len(w.name)}) == 0) "
            f"{{ fread({w.symbol}, sizeof {w.symbol}, 1, f); return 0; }}")
    lines += ["    return 7;", "}", ""]
    return lines


def _emit_init(plan: Plan) -> list:
    m = plan.model
    dtype_code = _DTYPE_CODE[plan.dtype]
    return [
        f"int {m}_init(const char *path) {{",
        '    FILE *f = fopen(path, "rb");',
        "    if (!f) return 1;",
        "    unsigned char magic[8];",
        "    fread(magic, 1, 8, f);",
        '    if (memcmp(magic, "ROSENNA1", 8) != 0) { fclose(f); return 2; }',
        "    int32_t version, dtype, endian, ntensors;",
        "    fread(&version, sizeof version, 1, f);",
        "    fread(&dtype, sizeof dtype, 1, f);",
        "    fread(&endian, sizeof endian, 1, f);",
        "    fread(&ntensors, sizeof ntensors, 1, f);",
        "    if (version != 1) { fclose(f); return 3; }",
        f"    if (dtype != {dtype_code}) {{ fclose(f); return 4; }}",
        "    if (endian != 0x01020304) { fclose(f); return 5; }",
        "    unsigned char file_hash[32];",
        "    fread(file_hash, 1, 32, f);",
        "    if (memcmp(file_hash, expected_hash, 32) != 0) { fclose(f); return 6; }",
        "    int32_t toclen;",
        "    fread(&toclen, sizeof toclen, 1, f);",
        "    long data_start = 60L + (long)toclen;",
        "    for (int32_t k = 0; k < ntensors; ++k) {",
        "        int32_t namelen;",
        "        fread(&namelen, sizeof namelen, 1, f);",
        "        char name[128];",
        "        fread(name, 1, (size_t)namelen, f);",
        "        int32_t rank;",
        "        fread(&rank, sizeof rank, 1, f);",
        "        int64_t dims[8];",
        "        fread(dims, sizeof(int64_t), (size_t)rank, f);",
        "        (void)dims;",
        "        int64_t off, length;",
        "        fread(&off, sizeof off, 1, f);",
        "        fread(&length, sizeof length, 1, f);",
        "        (void)length;",
        "        long tocpos = ftell(f);",
        "        int status = load_tensor(f, name, namelen, data_start + (long)off);",
        "        if (status != 0) { fclose(f); return status; }",
        "        fseek(f, tocpos, SEEK_SET);",
        "    }",
        "    fclose(f);",
        "    return 0;",
        "}",
        "",
    ]


def _emit_infer(plan: Plan, ctype: str) -> list:
    m = plan.model
    n_in = plan.input.shape[0]
    weight_by_symbol = {w.symbol: w for w in plan.weights}
    steps = _fuse(plan.ops)
    buffers, assignment = _assign_buffers_c(plan, steps)
    scratch = sorted((s for s in buffers if s not in ("x", "y")), key=lambda s: int(s[1:]))

    lines = [f"void {m}_infer(const {ctype} *restrict x, {ctype} *restrict y) {{"]
    for sym in scratch:
        lines.append(f"    {ctype} {sym}[{buffers[sym]}];")

    cur_len = n_in
    for s in steps:
        dst, src = assignment[s["out"]], assignment[s["inp"]]
        if s["kind"] == "gemm":
            idx_expr = _weight_index_c(weight_by_symbol, s["weight"], s["n_in"], s["n_out"])
            lines.append(f"    for (int i = 0; i < {s['n_out']}; ++i) {{")
            bias_init = f"{s['bias']}[i]" if s["bias"] else "0.0"
            lines.append(f"        {ctype} acc = {bias_init};")
            lines.append(
                f"        for (int j = 0; j < {s['n_in']}; ++j) acc += {src}[j] * {s['weight']}[{idx_expr}];")
            if s["act"]:
                expr = _ACT_C[s["act"]].format(v="acc")
                lines.append(f"        {dst}[i] = {expr};")
            else:
                lines.append(f"        {dst}[i] = acc;")
            lines.append("    }")
            cur_len = s["n_out"]
        else:
            expr = _ACT_C[s["act"]].format(v=f"{src}[i]")
            lines.append(f"    for (int i = 0; i < {cur_len}; ++i) {dst}[i] = {expr};")

    lines.append("}")
    lines.append("")
    return lines
