"""Render a plan as a self-contained C source/header pair."""
from .plan import Plan

_CTYPE = {"f32": "float", "f64": "double"}
_ACT_C = {"relu": "{v} > 0.0 ? {v} : 0.0", "tanh": "tanh({v})",
          "sigmoid": "1.0 / (1.0 + exp(-({v})))"}
_DTYPE_CODE = {"f32": 0, "f64": 1}


def _c_string(s: str) -> str:
    """Escape a plan-supplied (ASCII) name as a C string literal body."""
    out = []
    for ch in s:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def _weight_size(shape) -> int:
    size = 1
    for d in shape:
        size *= d
    return size


def _weight_index_c(weight_by_symbol: dict, op) -> str:
    """Decide the accumulation index order from the op's own transB flag.

    A transB=1 Gemm weight has ONNX shape (n_out, n_in), stored row-major and
    indexed w[i * n_in + j]. A transB=0 weight, or any MatMul weight, has
    ONNX shape (n_in, n_out), indexed w[j * n_out + i]. Unlike the Fortran
    side, C never reverses the dimensions, so no transposition happens
    anywhere.

    The flag is authoritative. The shape check below only makes a plan that
    disagrees with its own weights fail loudly; sniffing the convention back
    out of the shape, which is what this replaces, is ambiguous exactly when
    n_in == n_out and silently transposes a square weight.
    """
    spec = weight_by_symbol[op.weight]
    expected = (op.n_out, op.n_in) if op.trans_b else (op.n_in, op.n_out)
    if tuple(spec.shape) != expected:
        raise AssertionError(
            f"weight {op.weight}: shape {tuple(spec.shape)} does not match the layout "
            f"the plan claims (transB={int(op.trans_b)} implies {expected})")
    return f"i * {op.n_in} + j" if op.trans_b else f"j * {op.n_out} + i"


def emit_c(plan: Plan) -> tuple:
    ctype = _CTYPE[plan.dtype]
    header = _emit_header(plan, ctype)
    lines = []
    lines += _emit_source_head(plan, ctype)
    lines += _emit_load(plan)
    lines += _emit_init(plan)
    lines += _emit_infer(plan, ctype)
    source = "\n".join(lines) + "\n"
    return source, header


def _emit_header(plan: Plan, ctype: str) -> str:
    m = plan.model
    guard = f"ROSENNA_{m.upper()}_H"
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "/* Generated by rosenna. Do not edit. */",
        "",
        f"int {m}_init(const char *path);",
        f"void {m}_infer(const {ctype} *restrict x, {ctype} *restrict y);",
        "",
        "#endif",
    ]
    return "\n".join(lines) + "\n"


def _emit_source_head(plan: Plan, ctype: str) -> list:
    m = plan.model
    hash_bytes = ", ".join(f"0x{b:02x}" for b in bytes.fromhex(plan.hash()))
    lines = [
        "/* Generated by rosenna. Do not edit. */",
        f'#include "{m}.h"',
        "",
        "#include <stdint.h>",
        "#include <stdio.h>",
        "#include <string.h>",
        "#include <math.h>",
        "",
        f"static const unsigned char expected_hash[32] = {{ {hash_bytes} }};",
        "",
    ]
    for w in plan.weights:
        lines.append(f"static {ctype} {w.symbol}[{_weight_size(w.shape)}];")
    lines.append("")
    return lines


def _emit_load(plan: Plan) -> list:
    lines = [
        "static int load_tensor(FILE *f, const char *name, int namelen, long pos) {",
        "    fseek(f, pos, SEEK_SET);",
    ]
    for w in plan.weights:
        lines.append(
            f"    if (namelen == {len(w.name)} && memcmp(name, {_c_string(w.name)}, {len(w.name)}) == 0) "
            f"{{ fread({w.symbol}, sizeof {w.symbol}, 1, f); return 0; }}")
    lines += ["    return 7;", "}", ""]
    return lines


def _emit_init(plan: Plan) -> list:
    m = plan.model
    dtype_code = _DTYPE_CODE[plan.dtype]
    return [
        f"int {m}_init(const char *path) {{",
        '    FILE *f = fopen(path, "rb");',
        "    if (!f) return 1;",
        "    unsigned char magic[8];",
        "    fread(magic, 1, 8, f);",
        '    if (memcmp(magic, "ROSENNA1", 8) != 0) { fclose(f); return 2; }',
        "    int32_t version, dtype, endian, ntensors;",
        "    fread(&version, sizeof version, 1, f);",
        "    fread(&dtype, sizeof dtype, 1, f);",
        "    fread(&endian, sizeof endian, 1, f);",
        "    fread(&ntensors, sizeof ntensors, 1, f);",
        "    if (version != 1) { fclose(f); return 3; }",
        f"    if (dtype != {dtype_code}) {{ fclose(f); return 4; }}",
        "    if (endian != 0x01020304) { fclose(f); return 5; }",
        "    unsigned char file_hash[32];",
        "    fread(file_hash, 1, 32, f);",
        "    if (memcmp(file_hash, expected_hash, 32) != 0) { fclose(f); return 6; }",
        "    int32_t toclen;",
        "    fread(&toclen, sizeof toclen, 1, f);",
        "    long data_start = 60L + (long)toclen;",
        "    for (int32_t k = 0; k < ntensors; ++k) {",
        "        int32_t namelen;",
        "        fread(&namelen, sizeof namelen, 1, f);",
        "        char name[128];",
        "        fread(name, 1, (size_t)namelen, f);",
        "        int32_t rank;",
        "        fread(&rank, sizeof rank, 1, f);",
        "        int64_t dims[8];",
        "        fread(dims, sizeof(int64_t), (size_t)rank, f);",
        "        (void)dims;",
        "        int64_t off, length;",
        "        fread(&off, sizeof off, 1, f);",
        "        fread(&length, sizeof length, 1, f);",
        "        (void)length;",
        "        long tocpos = ftell(f);",
        "        int status = load_tensor(f, name, namelen, data_start + (long)off);",
        "        if (status != 0) { fclose(f); return status; }",
        "        fseek(f, tocpos, SEEK_SET);",
        "    }",
        "    fclose(f);",
        "    return 0;",
        "}",
        "",
    ]


def _emit_infer(plan: Plan, ctype: str) -> list:
    """Emit the inference loop nest straight from plan.buffers / plan.assignment.

    There is deliberately no fusion pass and no private allocator here. The
    plan already owns the buffer assignment, one allocator serves both
    backends, and the plan hash covers what it produced. A second allocator
    with narrower assumptions (ruling R13) crashed on models validate accepts
    and the Fortran backend handles: a graph whose first node is an activation
    had no preceding gemm to take a length from, and a gemm output with two
    consumers lost its buffer to fusion and then could not be looked up.
    Fusion, if ever wanted, belongs in plan.py where one allocator serves both
    backends and the hash covers it.
    """
    m = plan.model
    n_in = plan.input.shape[0]
    weight_by_symbol = {w.symbol: w for w in plan.weights}
    scratch = sorted((s for s in plan.buffers if s not in ("x", "y")),
                     key=lambda s: int(s[1:]))

    lines = [f"void {m}_infer(const {ctype} *restrict x, {ctype} *restrict y) {{"]
    for sym in scratch:
        lines.append(f"    {ctype} {sym}[{plan.buffers[sym]}];")

    cur_len = n_in
    for op in plan.ops:
        dst, src = plan.assignment[op.out], plan.assignment[op.inp]
        if op.kind == "gemm":
            idx_expr = _weight_index_c(weight_by_symbol, op)
            bias_init = f"{op.bias}[i]" if op.bias else "0.0"
            lines.append(f"    for (int i = 0; i < {op.n_out}; ++i) {{")
            lines.append(f"        {ctype} acc = {bias_init};")
            lines.append(
                f"        for (int j = 0; j < {op.n_in}; ++j) "
                f"acc += {src}[j] * {op.weight}[{idx_expr}];")
            lines.append(f"        {dst}[i] = acc;")
            lines.append("    }")
            cur_len = op.n_out
        elif op.kind in _ACT_C:
            expr = _ACT_C[op.kind].format(v=f"{src}[i]")
            lines.append(f"    for (int i = 0; i < {cur_len}; ++i) {dst}[i] = {expr};")
        else:
            raise AssertionError(f"unhandled op kind {op.kind!r}")

    lines.append("}")
    lines.append("")
    return lines
