"""Render <name>_kernel.cu: the native device kernels for nvcc and hipcc.

One source in the CUDA subset hipcc accepts unchanged; every runtime call
goes through rosenna_rt.h. Two entry points:

infer_batch: one thread per point calling the header's infer, whose dense
layers are register-blocked (emit_c.GEMM_BLOCK). Staging the weights in
shared memory was tried and measured slower on an MI210; the bound was the
per-thread activation loads, which the blocking amortises.

infer_one: one sample, a launch per op with the thread index over the op's
output elements and the intermediate activations in static __device__
buffers. The form a model over a whole field needs; absent when the plan
has an LSTM. Those buffers are shared by every call, so infer_one orders
itself across streams with an event (status 12 if the event API fails).

Both are asynchronous on the caller's stream (ruling R5); the one transfer
this file makes (<name>_device_bind, file-loaded plans) is the plan step,
called from init. Validated on an A100 (nvcc 13.0, HPC SDK 25.11) and an
MI210 (ROCm 7.2.0, AFAR 23.2.1) by `rosenna gpu-gate`.
"""
from .emit_c import (KERNEL_TILE, _CTYPE, _c_weight_symbol, _device_bind, elem_call, elem_length,
                     field_buffer, has_infer_one, large_locals, scratch_symbols)
from .plan import Plan


def emit_kernel(plan: Plan) -> str:
    m = plan.model
    ctype = _CTYPE[plan.dtype]
    n_in, n_out = plan.input.shape[0], plan.output.shape[0]
    dev_check = ([f"    if ({_c_weight_symbol(m, w.symbol)}_dev == 0) return 10;" for w in plan.weights]
                 if not plan.embed and plan.weights else [])
    lines = [
        "/* Generated by rosenna. Do not edit. Build with nvcc or hipcc. */",
        '#include "rosenna_rt.h"',
        f'#include "{m}.h"',
        "",
        "#include <stddef.h>",
        "",
        f"#define ROSENNA_TILE {KERNEL_TILE}",
        "",
    ]
    if not plan.embed and plan.weights:
        lines += [
            "/* Plan step (controller ruling R5), called by init after it has made",
            "   the device copies: binds this translation unit's __constant__ table,",
            "   the one the kernel below reads, through the header's",
            f"   {_device_bind(m)}_here. Nothing else in this file transfers. */",
            f'extern "C" int {_device_bind(m)}(void) {{',
            f"    return {_device_bind(m)}_here();",
            "}",
            "",
        ]

    # --- infer_one ---
    if has_infer_one(plan):
        lines += ["/* infer_one's activations: device globals, referenced by name from the",
                  "   kernels (a __device__ variable's address is not a host value). */"]
        lines += [f"static __device__ {ctype} {field_buffer(m, sym)}[{plan.buffers[sym]}];"
                  for sym in scratch_symbols(plan)]
        lines.append("")
        for k, op in enumerate(plan.ops):
            if op.kind == "alias":
                continue
            lines += [
                f"static __global__ void {m}_k{k}(const {ctype} *__restrict__ x, {ctype} *__restrict__ y) {{",
                "    const int e = (int)(blockIdx.x * blockDim.x + threadIdx.x);",
                f"    if (e < {elem_length(op)}) {elem_call(plan, k, op)};",
                "}",
            ]
        lines += [
            "",
            "/* The activation buffers above are shared by every infer_one call, so two",
            "   calls must not overlap. Calls on one stream are already ordered by the",
            "   stream itself; a call on a different stream is made to wait on an event",
            "   recorded after the previous call's last launch. Both the wait and the",
            "   record are asynchronous enqueues -- the loop path still never",
            "   synchronizes (ruling R5) -- and the event is created once, on the first",
            "   call, never again.",
            "",
            "   This orders the device work. It does not make infer_one callable from",
            "   several host threads at once: the two statics below are plain host",
            "   state with no lock. */",
            f"static ROSENNA_EVENT_T {m}_one_done;",
            f"static int {m}_one_ready = 0;",
            f"static ROSENNA_STREAM_T {m}_one_stream;",
            "",
            f'extern "C" int {m}_infer_one(const {ctype} *__restrict__ x, {ctype} *__restrict__ y, void *stream) {{',
            "    const ROSENNA_STREAM_T s = (ROSENNA_STREAM_T)stream;",
            *dev_check,
            f"    if (!{m}_one_ready) {{",
            f"        if (ROSENNA_EVENT_CREATE(&{m}_one_done) != ROSENNA_OK) return 12;",
            f"        {m}_one_ready = 1;",
            f"    }} else if (s != {m}_one_stream) {{",
            f"        if (ROSENNA_STREAM_WAIT_EVENT(s, {m}_one_done) != ROSENNA_OK) return 12;",
            "    }",
            f"    {m}_one_stream = s;",
        ]
        for k, op in enumerate(plan.ops):
            if op.kind == "alias":
                continue
            n = elem_length(op)
            lines += [f"    ROSENNA_LAUNCH({m}_k{k}, ({n} + ROSENNA_TILE - 1) / ROSENNA_TILE, ROSENNA_TILE, s, x, y);",
                      "    if (ROSENNA_LAUNCH_STATUS() != ROSENNA_OK) return 11;"]
        lines += [
            f"    if (ROSENNA_EVENT_RECORD({m}_one_done, s) != ROSENNA_OK) return 12;",
            "    return 0;", "}", ""]

    # --- infer_batch ---
    if large_locals(plan):
        lines += [
            f"/* {m}_infer's locals exceed a device thread's stack: infer_batch runs",
            "   infer_one per point, each a launch per op over the static buffers. */",
            f'extern "C" int {m}_infer_batch(int n, const {ctype} *__restrict__ x, {ctype} *__restrict__ y, void *stream) {{',
            "    int status = 0;",
            "    for (int p = 0; p < n && status == 0; ++p)",
            f"        status = {m}_infer_one(x + (size_t)p * {n_in}, y + (size_t)p * {n_out}, stream);",
            "    return status;",
            "}",
            "",
        ]
    else:
        lines += [
            "/* One thread per point; each calls the same inline body the host uses,",
            "   now instantiated as a __device__ function. */",
            f"static __global__ void {m}_kernel(int n, const {ctype} *__restrict__ x,",
            f"                                  {ctype} *__restrict__ y) {{",
            "    const int p = (int)(blockIdx.x * blockDim.x + threadIdx.x);",
            "    if (p >= n) return;",
            f"    {m}_infer(x + (size_t)p * {n_in}, y + (size_t)p * {n_out});",
            "}",
            "",
        ]
        lines += [
            f'extern "C" int {m}_infer_batch(int n, const {ctype} *__restrict__ x, {ctype} *__restrict__ y, void *stream) {{',
            "    if (n <= 0) return 0;",
            "    const ROSENNA_STREAM_T s = (ROSENNA_STREAM_T)stream;",
            # A null device copy means init never ran or failed: status 10 rather
            # than a device fault. Reading the host globals is not a transfer.
            *dev_check,
            "    const int grid = (n + ROSENNA_TILE - 1) / ROSENNA_TILE;",
            f"    ROSENNA_LAUNCH({m}_kernel, grid, ROSENNA_TILE, s, n, x, y);",
            "    /* GetLastError, not a sync (ruling R5): a bad configuration or stream",
            "       is reported now; asynchronous faults surface at the caller's sync. */",
            "    if (ROSENNA_LAUNCH_STATUS() != ROSENNA_OK) return 11;",
            "    return 0;",
            "}",
            "",
        ]

    lines += [
        "/* The one synchronization in this file, and only when the caller asks:",
        "   a host with no stream of its own (an OpenMP host) waits here before",
        "   its next target region reads y. */",
        f'extern "C" int {m}_sync(void *stream) {{',
        "    return ROSENNA_SYNC((ROSENNA_STREAM_T)stream) == ROSENNA_OK ? 0 : 11;",
        "}",
        "",
    ]
    return "\n".join(lines)
