"""Render a plan as a self-contained Fortran module."""
from .plan import Plan

_KIND = {"f32": "real32", "f64": "real64"}
_ACT = {"relu": "max({v}, 0.0_wp)", "tanh": "tanh({v})", "sigmoid": "1.0_wp / (1.0_wp + exp(-({v})))"}
_DTYPE_CODE = {"f32": 0, "f64": 1}


def _weight_dims(plan: Plan, symbol: str) -> str:
    spec = next(w for w in plan.weights if w.symbol == symbol)
    return "(" + ",".join(str(d) for d in reversed(spec.shape)) + ")"


def emit_fortran(plan: Plan) -> str:
    m, wp = plan.model, _KIND[plan.dtype]
    # Wrap each literal in an explicit int(..., int8) conversion: an
    # unsuffixed literal is default INTEGER(4), and initializing an
    # INTEGER(1) parameter array from those trips gfortran's -Wconversion
    # under -Wextra. A plain "_int8" kind suffix does not work either --
    # gfortran checks a literal's unsigned magnitude against the kind's
    # range before applying unary minus, so "-128_int8" is rejected as
    # "Integer too big for its kind" even though -128 is in range.
    hash_bytes = ", ".join(f"int({b if b < 128 else b - 256}, int8)" for b in bytes.fromhex(plan.hash()))
    lines = [
        f"module {m}_model",
        "    ! Generated by rosenna. Do not edit.",
        "    use iso_fortran_env, only: int8, int32, int64, " + wp,
        "    implicit none",
        "    private",
        f"    public :: {m}_init, {m}_infer",
        "",
        f"    integer, parameter :: wp = {wp}",
        f"    integer(int8), parameter :: expected_hash(32) = [ {hash_bytes} ]",
    ]
    for w in plan.weights:
        lines.append(f"    real(wp), protected :: {w.symbol}{_weight_dims(plan, w.symbol)}")
    lines += ["", "contains", ""]
    lines += _emit_init(plan)
    lines += _emit_load(plan)
    lines += _emit_infer(plan)
    lines.append(f"end module {m}_model")
    return "\n".join(lines) + "\n"


def _emit_init(plan: Plan) -> list:
    m = plan.model
    dtype_code = _DTYPE_CODE[plan.dtype]
    return [
        f"    subroutine {m}_init(path, status)",
        "        character(*), intent(in) :: path",
        "        integer, intent(out) :: status",
        "        integer :: u, ios, ntensors, toclen, k, namelen, rank",
        "        integer(int32) :: version, dtype, endian",
        "        integer(int64) :: dims(8), off, length, data_start, tocpos",
        "        character(len=8) :: magic",
        "        character(len=128) :: name",
        "        integer(int8) :: file_hash(32)",
        "        status = 0",
        "        open(newunit=u, file=path, status='old', action='read', access='stream', &",
        "             form='unformatted', iostat=ios)",
        "        if (ios /= 0) then; status = 1; return; end if",
        "        read(u) magic",
        "        if (magic /= 'ROSENNA1') then; status = 2; close(u); return; end if",
        "        read(u) version, dtype, endian, ntensors",
        "        if (version /= 1) then; status = 3; close(u); return; end if",
        f"        if (dtype /= {dtype_code}) then; status = 4; close(u); return; end if",
        "        if (endian /= 16909060) then; status = 5; close(u); return; end if",
        "        read(u) file_hash",
        "        if (any(file_hash /= expected_hash)) then; status = 6; close(u); return; end if",
        "        read(u) toclen",
        "        data_start = int(60, int64) + int(toclen, int64) + 1_int64",
        "        do k = 1, ntensors",
        "            read(u) namelen",
        "            name = ''",
        "            read(u) name(1:namelen)",
        "            read(u) rank",
        "            read(u) dims(1:rank)",
        "            read(u) off, length",
        "            inquire(unit=u, pos=tocpos)",
        "            call load_tensor(u, name(1:namelen), data_start + off, status)",
        "            if (status /= 0) then; close(u); return; end if",
        "            read(u, pos=tocpos)",
        "        end do",
        "        close(u)",
        "    end subroutine",
        "",
    ]


def _emit_load(plan: Plan) -> list:
    lines = [
        "    subroutine load_tensor(u, name, pos, status)",
        "        integer, intent(in) :: u",
        "        character(*), intent(in) :: name",
        "        integer(int64), intent(in) :: pos",
        "        integer, intent(out) :: status",
        "        status = 0",
        "        select case (name)",
    ]
    for w in plan.weights:
        lines.append(f"        case ('{w.name}'); read(u, pos=pos) {w.symbol}")
    lines += [
        "        case default; status = 7",
        "        end select",
        "    end subroutine",
        "",
    ]
    return lines


def _weight_index(weight_by_symbol: dict, op) -> str:
    """Decide the accumulation index order from the op's own transB flag.

    A transB=1 Gemm weight has ONNX shape (n_out, n_in): Fortran dims are
    (n_in, n_out) and the accumulation reads w(j, i). A transB=0 weight, or
    any MatMul weight, has ONNX shape (n_in, n_out): Fortran dims are
    (n_out, n_in) and the accumulation reads w(i, j).

    The flag is authoritative; the shape check below only makes a plan that
    disagrees with its own weights fail loudly instead of silently reading a
    transposed array. Sniffing the convention back out of the shape is what
    this replaces: when n_in == n_out the two cases are indistinguishable.
    """
    spec = weight_by_symbol[op.weight]
    expected = (op.n_out, op.n_in) if op.trans_b else (op.n_in, op.n_out)
    if tuple(spec.shape) != expected:
        raise AssertionError(
            f"weight {op.weight}: shape {tuple(spec.shape)} does not match the layout "
            f"the plan claims (transB={int(op.trans_b)} implies {expected})")
    return "j, i" if op.trans_b else "i, j"


def _emit_infer(plan: Plan) -> list:
    m = plan.model
    n_in, n_out = plan.input.shape[0], plan.output.shape[0]
    weight_by_symbol = {w.symbol: w for w in plan.weights}
    scratch = sorted((s for s in plan.buffers if s not in ("x", "y")),
                      key=lambda s: int(s[1:]))

    lines = [
        f"    pure subroutine {m}_infer(x, y)",
        f"        real(wp), intent(in) :: x({n_in})",
        f"        real(wp), intent(out) :: y({n_out})",
    ]
    for sym in scratch:
        lines.append(f"        real(wp) :: {sym}({plan.buffers[sym]})")
    lines.append("        integer :: i, j")

    # Fusing an activation into its preceding gemm's loop would require the
    # activation's output buffer to equal the gemm's output buffer. Task 4's
    # _assign_buffers can never produce that: an op's output symbol is
    # assigned before its input's symbol is returned to the free list, so no
    # op -- activation or otherwise -- can ever share a buffer with its own
    # input. That makes the fusion case unreachable by construction, not by
    # coincidence, so there is no such branch here: every op gets its own
    # loop, straight from plan.assignment and plan.buffers.
    ops = plan.ops
    cur_len = n_in
    for op in ops:
        if op.kind == "gemm":
            dst = plan.assignment[op.out]
            src = plan.assignment[op.inp]
            idx_expr = _weight_index(weight_by_symbol, op)

            lines.append(f"        do i = 1, {op.n_out}")
            if op.bias:
                lines.append(f"            {dst}(i) = {op.bias}(i)")
            else:
                lines.append(f"            {dst}(i) = 0.0_wp")
            lines.append(f"            do j = 1, {op.n_in}")
            lines.append(f"                {dst}(i) = {dst}(i) + {src}(j) * {op.weight}({idx_expr})")
            lines.append("            end do")
            lines.append("        end do")
            cur_len = op.n_out
        elif op.kind in _ACT:
            dst = plan.assignment[op.out]
            src = plan.assignment[op.inp]
            lines.append(f"        do i = 1, {cur_len}")
            lines.append(f"            {dst}(i) = {_ACT[op.kind].format(v=f'{src}(i)')}")
            lines.append("        end do")
        else:
            raise AssertionError(f"unhandled op kind {op.kind!r}")

    lines.append("    end subroutine")
    lines.append("")
    return lines
