"""Render <name>_kernel.cu: the native batched kernel for nvcc and hipcc.

One source in the CUDA subset hipcc accepts unchanged; every runtime call
goes through rosenna_rt.h. The kernel is one thread per point calling the
header-inline infer, which is correct by construction because it reuses the
body every host test already checks; a fused tiled GEMM over the batch is a
follow-up once the GPU gate has timed this one. Controller ruling R5: x and
y are device-resident and infer_batch only launches; the one transfer this
file makes (<name>_device_bind, file-loaded plans only) belongs to the plan
step and is called from init. Compiles and runs on the host (through the
omp backend) only; the device path is unvalidated until nvcc has built it
on CI and the GPU gate has run it.
"""
from .emit_c import KERNEL_TILE, _CTYPE, _c_weight_symbol, _device_bind, _device_weight_table
from .plan import Plan


def emit_kernel(plan: Plan) -> str:
    m = plan.model
    ctype = _CTYPE[plan.dtype]
    n_in, n_out = plan.input.shape[0], plan.output.shape[0]
    lines = [
        "/* Generated by rosenna. Do not edit. Build with nvcc or hipcc. */",
        '#include "rosenna_rt.h"',
        f'#include "{m}.h"',
        "",
        "#include <stddef.h>",
        "",
        f"#define ROSENNA_TILE {KERNEL_TILE}",
        "",
    ]
    if not plan.embed and plan.weights:
        table = _device_weight_table(m)
        nw = len(plan.weights)
        lines += [
            "/* Plan step (controller ruling R5), called by init after it has made",
            "   the device copies: publishes their addresses to this translation",
            "   unit's __constant__ table, the one the kernel below reads. This is",
            "   the only transfer in this file; infer_batch launches and nothing",
            "   else. */",
            f'extern "C" int {_device_bind(m)}(void) {{',
            f"    const {ctype} *table[{nw}] = {{",
        ]
        for w in plan.weights:
            lines.append(f"        {_c_weight_symbol(m, w.symbol)}_dev,")
        lines += [
            "    };",
            f"    for (int k = 0; k < {nw}; ++k) if (table[k] == 0) return 10;",
            f"    if (ROSENNA_MEMCPY_TO_SYMBOL({table}, table, sizeof table) != ROSENNA_OK) return 10;",
            "    return 0;",
            "}",
            "",
        ]
    lines += [
        "/* One thread per point; each calls the same inline body the host uses,",
        "   now instantiated as a __device__ function. */",
        f"static __global__ void {m}_kernel(int n, const {ctype} *__restrict__ x,",
        f"                                  {ctype} *__restrict__ y) {{",
        "    const int p = (int)(blockIdx.x * blockDim.x + threadIdx.x);",
        "    if (p >= n) return;",
        f"    {m}_infer(x + (size_t)p * {n_in}, y + (size_t)p * {n_out});",
        "}",
        "",
        f'extern "C" int {m}_infer_batch(int n, const {ctype} *x, {ctype} *y, void *stream) {{',
        "    if (n <= 0) return 0;",
        "    const ROSENNA_STREAM_T s = (ROSENNA_STREAM_T)stream;",
    ]
    if not plan.embed and plan.weights:
        # A null device copy means init never ran or failed: status 10 rather
        # than a device fault. Reading the host globals is not a transfer.
        lines += [f"    if ({_c_weight_symbol(m, w.symbol)}_dev == 0) return 10;" for w in plan.weights]
    lines += [
        "    const int grid = (n + ROSENNA_TILE - 1) / ROSENNA_TILE;",
        f"    ROSENNA_LAUNCH({m}_kernel, grid, ROSENNA_TILE, s, n, x, y);",
        "    return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)
