"""Render <name>_kernel.cu: the native batched kernel for nvcc and hipcc.

One source in the CUDA subset hipcc accepts unchanged; every runtime call
goes through rosenna_rt.h. The kernel is one thread per point calling the
header-inline infer, which is correct by construction because it reuses the
body every host test already checks; a fused tiled GEMM over the batch is a
follow-up once the GPU gate has timed this one. Controller ruling R5: x and
y are device-resident and infer_batch only launches; the one transfer this
file makes (<name>_device_bind, file-loaded plans only) belongs to the plan
step and is called from init. Compiles and runs on the host (through the
omp backend) only; the device path is unvalidated until nvcc has built it
on CI and the GPU gate has run it.
"""
from .emit_c import KERNEL_TILE, _CTYPE, _c_weight_symbol, _device_bind
from .plan import Plan


def emit_kernel(plan: Plan) -> str:
    m = plan.model
    ctype = _CTYPE[plan.dtype]
    n_in, n_out = plan.input.shape[0], plan.output.shape[0]
    lines = [
        "/* Generated by rosenna. Do not edit. Build with nvcc or hipcc. */",
        '#include "rosenna_rt.h"',
        f'#include "{m}.h"',
        "",
        "#include <stddef.h>",
        "",
        f"#define ROSENNA_TILE {KERNEL_TILE}",
        "",
    ]
    if not plan.embed and plan.weights:
        lines += [
            "/* Plan step (controller ruling R5), called by init after it has made",
            "   the device copies: binds this translation unit's __constant__ table,",
            "   the one the kernel below reads, through the header's",
            f"   {_device_bind(m)}_here. Nothing else in this file transfers. */",
            f'extern "C" int {_device_bind(m)}(void) {{',
            f"    return {_device_bind(m)}_here();",
            "}",
            "",
        ]
    lines += [
        "/* One thread per point; each calls the same inline body the host uses,",
        "   now instantiated as a __device__ function. */",
        f"static __global__ void {m}_kernel(int n, const {ctype} *__restrict__ x,",
        f"                                  {ctype} *__restrict__ y) {{",
        "    const int p = (int)(blockIdx.x * blockDim.x + threadIdx.x);",
        "    if (p >= n) return;",
        f"    {m}_infer(x + (size_t)p * {n_in}, y + (size_t)p * {n_out});",
        "}",
        "",
        f'extern "C" int {m}_infer_batch(int n, const {ctype} *__restrict__ x, {ctype} *__restrict__ y, void *stream) {{',
        "    if (n <= 0) return 0;",
        "    const ROSENNA_STREAM_T s = (ROSENNA_STREAM_T)stream;",
    ]
    if not plan.embed and plan.weights:
        # A null device copy means init never ran or failed: status 10 rather
        # than a device fault. Reading the host globals is not a transfer.
        lines += [f"    if ({_c_weight_symbol(m, w.symbol)}_dev == 0) return 10;" for w in plan.weights]
    lines += [
        "    const int grid = (n + ROSENNA_TILE - 1) / ROSENNA_TILE;",
        f"    ROSENNA_LAUNCH({m}_kernel, grid, ROSENNA_TILE, s, n, x, y);",
        "    /* GetLastError, not a sync (ruling R5): a bad configuration or stream",
        "       is reported now; asynchronous faults surface at the caller's sync. */",
        "    if (ROSENNA_LAUNCH_STATUS() != ROSENNA_OK) return 11;",
        "    return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)
