"""Render rosenna_rt.h: the one file that names the CUDA or HIP runtime API.

The generated kernel (`emit_kernel`) and the CUDA/HIP branch of the generated
`.c` reach the runtime only through these macros, so one source builds under
both nvcc and hipcc. The file is identical for every model.
"""

_RT_HEADER = """\
/* Generated by rosenna. Do not edit.
   Maps the runtime calls the generated sources make onto CUDA or HIP; no
   other generated file names a cuda* or hip* symbol. Compiled only by nvcc
   (__CUDACC__) or hip-clang (__HIPCC__): a host C compiler never sees it.
   __HIP__ is deliberately not tested: clang's OpenMP AMDGPU device pass
   defines it without being a HIP compilation. */
#ifndef ROSENNA_RT_H
#define ROSENNA_RT_H
#if defined(__HIPCC__)
#include <hip/hip_runtime.h>
#define ROSENNA_STREAM_T hipStream_t
#define ROSENNA_MALLOC(p, n) hipMalloc((void **)(p), (n))
#define ROSENNA_MEMCPY_H2D(d, h, n) hipMemcpy((d), (h), (n), hipMemcpyHostToDevice)
/* HIP_SYMBOL is how HIP spells a symbol argument portably: it expands to X
   on hip-clang and to &X on the retired hcc path. */
#define ROSENNA_MEMCPY_TO_SYMBOL(sym, src, n) \\
    hipMemcpyToSymbol(HIP_SYMBOL(sym), (src), (n), 0, hipMemcpyHostToDevice)
#define ROSENNA_FREE(p) hipFree(p)
#define ROSENNA_OK hipSuccess
#define ROSENNA_SYNC(s) hipStreamSynchronize(s)
#define ROSENNA_LAUNCH(k, g, b, s, ...) k<<<(g), (b), 0, (s)>>>(__VA_ARGS__)
#define ROSENNA_LAUNCH_STATUS() hipGetLastError()
/* Events, for infer_one's cross-stream ordering. Creating one is a host call;
   recording and waiting are asynchronous enqueues, not host synchronization. */
#define ROSENNA_EVENT_T hipEvent_t
#define ROSENNA_EVENT_CREATE(e) hipEventCreateWithFlags((e), hipEventDisableTiming)
#define ROSENNA_EVENT_RECORD(e, s) hipEventRecord((e), (s))
#define ROSENNA_STREAM_WAIT_EVENT(s, e) hipStreamWaitEvent((s), (e), 0)
#elif defined(__CUDACC__)
#include <cuda_runtime.h>
#define ROSENNA_STREAM_T cudaStream_t
#define ROSENNA_MALLOC(p, n) cudaMalloc((void **)(p), (n))
#define ROSENNA_MEMCPY_H2D(d, h, n) cudaMemcpy((d), (h), (n), cudaMemcpyHostToDevice)
#define ROSENNA_MEMCPY_TO_SYMBOL(sym, src, n) \\
    cudaMemcpyToSymbol((sym), (src), (n), 0, cudaMemcpyHostToDevice)
#define ROSENNA_FREE(p) cudaFree(p)
#define ROSENNA_OK cudaSuccess
#define ROSENNA_SYNC(s) cudaStreamSynchronize(s)
#define ROSENNA_LAUNCH(k, g, b, s, ...) k<<<(g), (b), 0, (s)>>>(__VA_ARGS__)
#define ROSENNA_LAUNCH_STATUS() cudaGetLastError()
#define ROSENNA_EVENT_T cudaEvent_t
#define ROSENNA_EVENT_CREATE(e) cudaEventCreateWithFlags((e), cudaEventDisableTiming)
#define ROSENNA_EVENT_RECORD(e, s) cudaEventRecord((e), (s))
#define ROSENNA_STREAM_WAIT_EVENT(s, e) cudaStreamWaitEvent((s), (e), 0)
#else
#error "rosenna_rt.h is for nvcc or hipcc only"
#endif
#endif
"""


def rt_header() -> str:
    return _RT_HEADER
