import re
import shutil
import subprocess
from pathlib import Path
import pytest
from rosenna.abi import STATUS_CODES
from tests.test_device_c import _omp_cc

README = Path(__file__).resolve().parents[1] / "README.md"


def _blocks(lang):
    text = README.read_text()
    return re.findall(rf"```{lang}\n(.*?)```", text, re.S)


def test_readme_has_every_required_section():
    text = README.read_text()
    for heading in ["What you get", "Install", "Generate", "Call it from C", "Call it from Fortran",
                    "Precision", "Status codes", "Verify", "Limits"]:
        assert f"## {heading}" in text, heading


def test_status_table_matches_abi():
    text = README.read_text()
    for code, meaning in STATUS_CODES:
        assert f"| {code} |" in text and meaning in text, (code, meaning)


def test_every_shell_command_in_the_readme_parses():
    # Each ```sh block is a sequence of commands the user is told to run; every one must at least
    # name a real subcommand or make target, so a renamed flag cannot leave the docs stale.
    from rosenna.cli import build_parser
    parser = build_parser()
    for block in _blocks("sh"):
        for line in block.strip().splitlines():
            if line.startswith("rosenna "):
                args = line.split()[1:]
                try:
                    parser.parse_args([a for a in args if not a.startswith("<")] or ["--help"])
                except SystemExit as e:
                    assert e.code == 0, line


def test_c_example_in_the_readme_compiles_and_runs(tmp_path, golden_model):
    # The README's C example is generated against gemm_small and must build and run as printed.
    from rosenna.cli import main
    assert main(["generate", str(golden_model("gemm_small")), "--lang", "c", "--precision", "double",
                 "--out", str(tmp_path), "--name", "model"]) == 0
    (blocks,) = [b for b in _blocks("c") if "model_infer(" in b][:1] or [None]
    assert blocks, "README has no C example calling model_infer"
    (tmp_path / "host.c").write_text(blocks)
    cc = _omp_cc()
    subprocess.run(["make", "-f", "model.mk", f"CC={cc}", "ROSENNA_OFFLOAD_FLAGS=-fopenmp"], cwd=tmp_path, check=True, capture_output=True, text=True)
    r = subprocess.run([cc, "-O2", "-std=c11", "-fopenmp", "host.c", "-L.", "-lmodel", "-lm", "-o", "host"], cwd=tmp_path, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    assert subprocess.run(["./host"], cwd=tmp_path, capture_output=True, text=True).returncode == 0


def test_fortran_example_in_the_readme_compiles_and_runs(tmp_path, golden_model):
    from rosenna.cli import main
    assert main(["generate", str(golden_model("gemm_small")), "--lang", "fortran", "--precision", "double",
                 "--out", str(tmp_path), "--name", "model"]) == 0
    (blocks,) = [b for b in _blocks("fortran") if "model_infer(" in b][:1] or [None]
    assert blocks, "README has no Fortran example calling model_infer"
    (tmp_path / "host.f90").write_text(blocks)
    fc = shutil.which("gfortran") or pytest.skip("no gfortran")
    subprocess.run(["make", "-f", "model_fortran.mk", f"FC={fc}", "ROSENNA_OFFLOAD_FLAGS=-fopenmp"], cwd=tmp_path, check=True, capture_output=True, text=True)
    # --lang fortran writes libmodel_f.a (model_fortran.mk), not libmodel.a: --lang
    # c/both's C recipe (model.mk -> libmodel.a) is not generated by this call, so the
    # link line below names the archive the Fortran recipe actually built.
    r = subprocess.run([fc, "-O2", "-std=f2008", "-fopenmp", "-I.", "host.f90", "-L.", "-lmodel_f", "-o", "host"], cwd=tmp_path, capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
    assert subprocess.run(["./host"], cwd=tmp_path, capture_output=True, text=True).returncode == 0
