name: CI

on:
  # all branches
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  CI_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Clone roseNNa
        uses: actions/checkout@v4

      - name: Set up gfortran
        uses: fortran-lang/setup-fortran@v1
        with:
          compiler: gcc
          version: 13

      - name: Check gfortran version
        run: gfortran --version

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run test cases
        run: |
          mkdir -p fLibrary/objFiles
          chmod +x test/run.sh
          cd test && ./run.sh
